version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=osmait
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
#  app:
#    build: .
#    command:  "java -jar facturationProject-0.0.1-SNAPSHOT.jar"
#    depends_on:
#      - postgres
#    ports:
#      - 8080:8080
#    environment:
#      DB_PORT: ${DB_PORT}
#      DB_DATABASE: ${DB_DATABASE}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_HOSTNAME: postgres
#      JWT_Key: ${JWT_Key}


